# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8aa7ec9bed7d246bfafa38c8c4a9f1a1b5bba343dc29fcd00e48d18986bfd374edaec7119a0c28fa4ac2aae74e61d077b8bd3ebf3499a8f2014a0e7c3b1d9e

test:
  secret_key_base: 135e3429e5b4217e1ce4849eb9509aa71ba8276a31edb244b3b54078eae1c7687e9aa224d352ee73bcb28e17524326bca96cafd640c5d1fe25165ba38f140cbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
